-- Generated by Oracle SQL Developer Data Modeler 24.3.1.347.1153
--   at:        2026-02-06 10:50:20 HNE
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE commande (
    id_commande                INTEGER NOT NULL,
    date_commande              DATE NOT NULL,
    addresse                   VARCHAR2(255) NOT NULL,
    ville                      VARCHAR2(255) NOT NULL,
    code_postal                VARCHAR2(255) NOT NULL,
    utilisateur_id_utilisateur INTEGER NOT NULL
);

ALTER TABLE commande ADD CONSTRAINT commande_pk PRIMARY KEY ( id_commande );

CREATE TABLE inventaire (
    id_inventaire                INTEGER NOT NULL,
    quantite_disponible          INTEGER NOT NULL,
    produit_id_produit           INTEGER NOT NULL,
    produit_commande_id_commande INTEGER NOT NULL
);

CREATE UNIQUE INDEX inventaire__idx ON
    inventaire (
        produit_id_produit
    ASC,
        produit_commande_id_commande
    ASC );

CREATE UNIQUE INDEX inventaire__idxv1 ON
    inventaire (
        produit_id_produit
    ASC );

ALTER TABLE inventaire ADD CONSTRAINT inventaire_pk PRIMARY KEY ( id_inventaire );

CREATE TABLE panier (
    id_panier                  INTEGER NOT NULL,
    quantite                   INTEGER NOT NULL,
    utilisateur_id_utilisateur INTEGER NOT NULL
);

CREATE UNIQUE INDEX panier__idx ON
    panier (
        utilisateur_id_utilisateur
    ASC );

ALTER TABLE panier ADD CONSTRAINT panier_pk PRIMARY KEY ( id_panier );

CREATE TABLE panier_produit (
    panier_id_panier   INTEGER NOT NULL,
    produit_id_produit INTEGER NOT NULL
);

ALTER TABLE panier_produit ADD CONSTRAINT relation_4_pk PRIMARY KEY ( panier_id_panier,
                                                                      produit_id_produit );

CREATE TABLE permission (
    lire                       CHAR(1) NOT NULL,
    modifier                   CHAR(1) NOT NULL,
    ajouter                    CHAR(1) NOT NULL,
    supprimer                  CHAR(1) NOT NULL,
    utilisateur_id_utilisateur INTEGER NOT NULL
);

CREATE UNIQUE INDEX permission__idx ON
    permission (
        utilisateur_id_utilisateur
    ASC );

CREATE TABLE produit (
    id_produit               INTEGER NOT NULL,
    nom                      VARCHAR2(255) NOT NULL,
    prix                     NUMBER NOT NULL,
    carte_texte              VARCHAR2(255),
    type                     VARCHAR2(255),
    artiste                  VARCHAR2(255),
    numero_carte             VARCHAR2(255),
    rarete                   VARCHAR2(255),
    attaque                  VARCHAR2(255),
    description              CLOB NOT NULL,
    commande_id_commande     INTEGER NOT NULL,
    inventaire_id_inventaire INTEGER NOT NULL
);

CREATE UNIQUE INDEX produit__idx ON
    produit (
        inventaire_id_inventaire
    ASC );

ALTER TABLE produit ADD CONSTRAINT produit_pk PRIMARY KEY ( id_produit );

CREATE TABLE produit_commande (
    commande_id_commande INTEGER NOT NULL,
    produit_id_produit   INTEGER NOT NULL
);

ALTER TABLE produit_commande ADD CONSTRAINT produit_commande_pk PRIMARY KEY ( commande_id_commande,
                                                                              produit_id_produit );

CREATE TABLE utilisateur (
    id_utilisateur   INTEGER NOT NULL,
    courriel         VARCHAR2(255) NOT NULL,
    mot_de_passe     VARCHAR2(255) NOT NULL,
    panier_id_panier INTEGER NOT NULL
);

CREATE UNIQUE INDEX utilisateur__idx ON
    utilisateur (
        panier_id_panier
    ASC );

ALTER TABLE utilisateur ADD CONSTRAINT utilisateur_pk PRIMARY KEY ( id_utilisateur );

ALTER TABLE commande
    ADD CONSTRAINT commande_utilisateur_fk FOREIGN KEY ( utilisateur_id_utilisateur )
        REFERENCES utilisateur ( id_utilisateur );

ALTER TABLE inventaire
    ADD CONSTRAINT inventaire_produit_fk FOREIGN KEY ( produit_id_produit )
        REFERENCES produit ( id_produit );

ALTER TABLE panier
    ADD CONSTRAINT panier_utilisateur_fk FOREIGN KEY ( utilisateur_id_utilisateur )
        REFERENCES utilisateur ( id_utilisateur );

ALTER TABLE permission
    ADD CONSTRAINT permission_utilisateur_fk FOREIGN KEY ( utilisateur_id_utilisateur )
        REFERENCES utilisateur ( id_utilisateur );

ALTER TABLE produit_commande
    ADD CONSTRAINT produit_commande_commande_fk FOREIGN KEY ( commande_id_commande )
        REFERENCES commande ( id_commande );

ALTER TABLE produit_commande
    ADD CONSTRAINT produit_commande_produit_fk FOREIGN KEY ( produit_id_produit )
        REFERENCES produit ( id_produit );

ALTER TABLE produit
    ADD CONSTRAINT produit_inventaire_fk FOREIGN KEY ( inventaire_id_inventaire )
        REFERENCES inventaire ( id_inventaire );

ALTER TABLE panier_produit
    ADD CONSTRAINT relation_4_panier_fk FOREIGN KEY ( panier_id_panier )
        REFERENCES panier ( id_panier );

ALTER TABLE panier_produit
    ADD CONSTRAINT relation_4_produit_fk FOREIGN KEY ( produit_id_produit )
        REFERENCES produit ( id_produit );

ALTER TABLE utilisateur
    ADD CONSTRAINT utilisateur_panier_fk FOREIGN KEY ( panier_id_panier )
        REFERENCES panier ( id_panier );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             6
-- ALTER TABLE                             17
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
