-- Generated by Oracle SQL Developer Data Modeler 24.3.1.347.1153
--   at:        2026-02-02 21:28:52 HNE
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE client (
    id_client    INTEGER NOT NULL,
    username     VARCHAR2(255),
    courriel     VARCHAR2(255) NOT NULL,
    mot_de_passe VARCHAR2(255) NOT NULL
);

ALTER TABLE client ADD CONSTRAINT client_pk PRIMARY KEY ( id_client );

CREATE TABLE commande (
    id_commande      INTEGER NOT NULL,
    client_id_client INTEGER NOT NULL,
    date_commande    DATE NOT NULL,
    addresse         VARCHAR2(255) NOT NULL,
    ville            VARCHAR2(255) NOT NULL,
    code_postal      VARCHAR2(255) NOT NULL
);

ALTER TABLE commande ADD CONSTRAINT commande_pk PRIMARY KEY ( id_commande );

CREATE TABLE inventaire (
    id_inventaire       INTEGER NOT NULL,
    quantite_disponible INTEGER NOT NULL,
    produit_id_produit  INTEGER NOT NULL
);

CREATE UNIQUE INDEX inventaire__idx ON
    inventaire (
        produit_id_produit
    ASC );

ALTER TABLE inventaire ADD CONSTRAINT inventaire_pk PRIMARY KEY ( id_inventaire );

CREATE TABLE panier (
    id_panier          INTEGER NOT NULL,
    produit_id_produit INTEGER,
    quantite           INTEGER NOT NULL,
    client_id_client   INTEGER NOT NULL
);

ALTER TABLE panier ADD CONSTRAINT panier_pk PRIMARY KEY ( id_panier );

CREATE TABLE produit (
    id_produit  INTEGER NOT NULL,
    nom         VARCHAR2(255) NOT NULL,
    description CLOB NOT NULL,
    prix        NUMBER NOT NULL,
    type        VARCHAR2(255) NOT NULL
);

ALTER TABLE produit ADD CONSTRAINT produit_pk PRIMARY KEY ( id_produit );

CREATE TABLE produit_commande (
    produit_id_produit   INTEGER NOT NULL,
    commande_id_commande INTEGER NOT NULL
);

ALTER TABLE produit_commande ADD CONSTRAINT produit_commande_pk PRIMARY KEY ( produit_id_produit,
                                                                              commande_id_commande );

ALTER TABLE commande
    ADD CONSTRAINT commande_client_fk FOREIGN KEY ( client_id_client )
        REFERENCES client ( id_client );

ALTER TABLE inventaire
    ADD CONSTRAINT inventaire_produit_fk FOREIGN KEY ( produit_id_produit )
        REFERENCES produit ( id_produit );

ALTER TABLE panier
    ADD CONSTRAINT panier_client_fk FOREIGN KEY ( client_id_client )
        REFERENCES client ( id_client );

ALTER TABLE panier
    ADD CONSTRAINT panier_produit_fk FOREIGN KEY ( produit_id_produit )
        REFERENCES produit ( id_produit );

ALTER TABLE produit_commande
    ADD CONSTRAINT produit_commande_commande_fk FOREIGN KEY ( commande_id_commande )
        REFERENCES commande ( id_commande );

ALTER TABLE produit_commande
    ADD CONSTRAINT produit_commande_produit_fk FOREIGN KEY ( produit_id_produit )
        REFERENCES produit ( id_produit );

CREATE SEQUENCE client_id_client_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER client_id_client_trg BEFORE
    INSERT ON client
    FOR EACH ROW
    WHEN ( new.id_client IS NULL )
BEGIN
    :new.id_client := client_id_client_seq.nextval;
END;
/

CREATE SEQUENCE commande_id_commande_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER commande_id_commande_trg BEFORE
    INSERT ON commande
    FOR EACH ROW
    WHEN ( new.id_commande IS NULL )
BEGIN
    :new.id_commande := commande_id_commande_seq.nextval;
END;
/

CREATE SEQUENCE inventaire_id_inventaire_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER inventaire_id_inventaire_trg BEFORE
    INSERT ON inventaire
    FOR EACH ROW
    WHEN ( new.id_inventaire IS NULL )
BEGIN
    :new.id_inventaire := inventaire_id_inventaire_seq.nextval;
END;
/

CREATE SEQUENCE panier_id_panier_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER panier_id_panier_trg BEFORE
    INSERT ON panier
    FOR EACH ROW
    WHEN ( new.id_panier IS NULL )
BEGIN
    :new.id_panier := panier_id_panier_seq.nextval;
END;
/

CREATE SEQUENCE produit_id_produit_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER produit_id_produit_trg BEFORE
    INSERT ON produit
    FOR EACH ROW
    WHEN ( new.id_produit IS NULL )
BEGIN
    :new.id_produit := produit_id_produit_seq.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             1
-- ALTER TABLE                             12
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           5
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          5
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
